services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mathesu
      POSTGRES_DB: expense_tracker
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/data/var/lib/postgresql/data
    networks: 
      - expense-tracker

  redis:
    image: redis
    container_name: redis-expense-tracker
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - expense-tracker

  app:
    build: .
    container_name: go-expense-tracker
    ports:
      - 2024:80
    depends_on:
      - db
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_USER: mathesu
      DB_PASSWORD: password
      DB_NAME: expense_tracker
    networks:
      - expense-tracker

volumes:
  redis_data:
  postgres_data:

networks:
  expense-tracker:
    driver: bridge
